# Generated by Django 4.0.4 on 2022-05-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tutee',
            field=models.BooleanField(default=False, verbose_name='tutee status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False, verbose_name='tutor status'),
        ),
    ]
