# Generated by Django 4.0.4 on 2022-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.IntegerField(default=''),
        ),
    ]
